from __future__ import annotations

from typing import AsyncIterator, Protocol

from .models import RealtimeEvent


class RealtimeDialogueSession(Protocol):
    async def connect(self) -> None: ...

    async def append_audio(self, pcm_base64: str) -> None: ...

    async def append_context_item(self, *, role: str, text: str, item_id: str) -> str: ...

    async def delete_context_item(self, item_id: str) -> None: ...

    async def submit_tool_result(self, *, call_id: str, output: str) -> None: ...

    async def request_response(self) -> None: ...

    async def cancel_response(self) -> None: ...

    def events(self) -> AsyncIterator[RealtimeEvent]: ...

    async def close(self) -> None: ...

