import React from 'react';
import { Image, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { VoiceCaptureState } from '../types/chat';
import { AppTheme, THEMES } from '../utils/theme';
export function VoiceInputBar({ mode, inputText, onInputChange, onToggleMode, onSendText, onSendImage, canSend, canSendImage, captureState, pressIn, pressMove, pressOut, theme = THEMES.light }: any) {
  const voice = mode === 'voice'; const recording = captureState === 'Recording' || captureState === 'CancelZone';
  return <View style={[styles.container, { backgroundColor: theme.inputBar, borderTopColor: theme.inputBorder }]}><TouchableOpacity style={styles.button} onPress={onToggleMode} disabled={recording}><Text style={{ color: theme.text, fontSize: 22 }}>{voice ? '⌨' : '🎙'}</Text></TouchableOpacity>{voice ? <View onStartShouldSetResponder={() => true} onResponderGrant={pressIn} onResponderMove={pressMove} onResponderRelease={pressOut} style={[styles.hold, { backgroundColor: recording ? theme.voicePressed : theme.voiceSurface }]}><Text style={{ color: theme.text }}>{captureState === 'CancelZone' ? '松开取消发送' : recording ? '松开发送' : '按住说话'}</Text></View> : <TextInput style={[styles.input, { backgroundColor: theme.inputBackground, color: theme.inputText }]} placeholder="给天依发消息..." placeholderTextColor={theme.placeholder} value={inputText} onChangeText={onInputChange} multiline />}{canSendImage ? <TouchableOpacity style={styles.button} onPress={onSendImage} disabled={recording}><Image source={require('../assets/images/image_button_activate.png')} style={styles.icon} /></TouchableOpacity> : null}{!voice ? <TouchableOpacity style={styles.button} onPress={onSendText} disabled={!canSend}><Image source={canSend ? require('../assets/images/send_button_activate.png') : require('../assets/images/send_button_un.png')} style={styles.icon} /></TouchableOpacity> : null}</View>;
}
const styles = StyleSheet.create({ container: { minHeight: 58, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 6, paddingVertical: 8 }, button: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' }, icon: { width: 32, height: 32 }, input: { flex: 1, minHeight: 40, maxHeight: 120, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8 }, hold: { flex: 1, minHeight: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' } });
